const DOCKER_ID = 'DOCKER_ID'
const DOCKER_IMAGE = 'DOCKER_IMAGE'
const DOCKER_IMAGE_TAG = 'DOCKER_IMAGE_TAG'

module.exports.DOCKER_ID = DOCKER_ID
module.exports.DOCKER_IMAGE = DOCKER_IMAGE
module.exports.DOCKER_IMAGE_TAG = DOCKER_IMAGE_TAG